{{- if .Values.crds.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "capsule-proxy.crds.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-3"
    {{- include "capsule-proxy.crds.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "capsule-proxy.crds.component" . | quote }}
    {{- include "capsule-proxy.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - jobs
  verbs:
  - create
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - delete
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "capsule-proxy.crds.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-2"
    {{- include "capsule-proxy.crds.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "capsule-proxy.crds.component" . | quote }}
    {{- include "capsule-proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "capsule-proxy.crds.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "capsule-proxy.crds.name" . }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}