{{- if .Values.crds.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "capsule-proxy.crds.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # create hook dependencies in the right order
    "helm.sh/hook-weight": "-4"
    {{- include "capsule-proxy.crds.annotations" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: {{ include "capsule-proxy.crds.component" . | quote }}
    {{- include "capsule-proxy.labels" . | nindent 4 }}
{{- end }}