{{- if .Values.autoscaling.enabled }}
  {{- if semverCompare "<1.23-0" $.Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2beta1
  {{- else }}
apiVersion: autoscaling/v2
  {{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "capsule-proxy.fullname" . }}
  labels:
    {{- include "capsule-proxy.labels" . | nindent 4 }}
    {{- if .Values.autoscaling.labels }}
      {{- toYaml .Values.autoscaling.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.autoscaling.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "capsule-proxy.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" $.Capabilities.KubeVersion.Version }}
        targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
        {{- end }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" $.Capabilities.KubeVersion.Version }}
        targetAverageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
        {{- end }}
    {{- end }}
    {{- if .Values.autoscaling.metrics }}
      {{- toYaml .Values.autoscaling.metrics | nindent 4 }}
    {{- end }}
{{- end }}
