{{- if $.Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "capsule-proxy.fullname" . }}
  labels:
    {{- include "capsule-proxy.labels" . | nindent 4 }}
    {{- if .Values.rbac.labels }}
      {{- toYaml .Values.rbac.labels | nindent 4 }}
    {{- end }}
  {{- with .Values.rbac.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "capsule-proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $.Values.rbac.clusterRole }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
